version: '3.8'

services:
  vosk:
    image: sskorol/vosk-server:0.3.27-pc
    volumes:
      - ./model:/opt/vosk-server/model
    environment:
      - SAMPLE_RATE=16000
      - PYTHONBUFFERED=1
      - PYTHONENCODING=utf-8
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]

    ports:
      - 192.168.1.23:2700:2700
