version: '3.8'

services:

  vosk_0:
    image: sskorol/vosk-server:0.3.27-pc
    volumes:
      - ./model:/opt/vosk-server/model
    environment:
      - VOSK_SAMPLE_RATE=8000
      - PYTHONBUFFERED=1
      - PYTHONENCODING=utf-8
      - VOSK_SERVER_PORT=2710
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

    ports:
      - 192.168.1.11:2710:2710

  vosk_1:
    image: sskorol/vosk-server:0.3.27-pc
    volumes:
      - ./model:/opt/vosk-server/model
    environment:
      - VOSK_SAMPLE_RATE=8000
      - PYTHONBUFFERED=1
      - PYTHONENCODING=utf-8
      - VOSK_SERVER_PORT=2711
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

    ports:
      - 192.168.1.11:2711:2711

  vosk_2:
    image: sskorol/vosk-server:0.3.27-pc
    volumes:
      - ./model:/opt/vosk-server/model
    environment:
      - VOSK_SAMPLE_RATE=8000
      - PYTHONBUFFERED=1
      - PYTHONENCODING=utf-8
      - VOSK_SERVER_PORT=2712
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]

    ports:
      - 192.168.1.11:2712:2712

  vosk_3:
    image: sskorol/vosk-server:0.3.27-pc
    volumes:
      - ./model:/opt/vosk-server/model
    environment:
      - VOSK_SAMPLE_RATE=8000
      - PYTHONBUFFERED=1
      - PYTHONENCODING=utf-8
      - VOSK_SERVER_PORT=2713
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['3']
            capabilities: [gpu]

    ports:
      - 192.168.1.11:2713:2713

  vosk_4:
    image: sskorol/vosk-server:0.3.27-pc
    volumes:
      - ./model:/opt/vosk-server/model
    environment:
      - VOSK_SAMPLE_RATE=8000
      - PYTHONBUFFERED=1
      - PYTHONENCODING=utf-8
      - VOSK_SERVER_PORT=2714
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['4']
            capabilities: [gpu]

    ports:
      - 192.168.1.11:2714:2714
